--------------------------------------------------------------------------------
-- Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 12.3
--  \   \         Application : xaw2vhdl
--  /   /         Filename : clock_sync.vhd
-- /___/   /\     Timestamp : 11/17/2010 15:04:39
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st /home/cs002/VHDL_Snake_Game/ipcore_dir/./clock_sync.xaw /home/cs002/VHDL_Snake_Game/ipcore_dir/./clock_sync
--Design Name: clock_sync
--Device: xc3s200-4ft256
--
-- Module clock_sync
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library UNISIM;
use UNISIM.Vcomponents.all;

entity clock_sync is
  port (CLKIN_IN    : in  std_logic;
         RST_IN     : in  std_logic;
         --CLKIN_IBUFG_OUT : out   std_logic; 
         CLK_25_0   : out std_logic;
         CLK_50_0   : out std_logic;
         --CLK0_OUT        : out   std_logic; 
         LOCKED_OUT : out std_logic);
end clock_sync;

architecture BEHAVIORAL of clock_sync is
  signal CLKDV_BUF    : std_logic;
--   signal CLKFB_IN        : std_logic;
  signal CLKIN_IBUFG  : std_logic;
  signal CLK0_BUF     : std_logic;
  signal GND_BIT      : std_logic;
  signal clk_50_0_int : std_logic;
  
begin
  
  CLK_50_0 <= clk_50_0_int;

  GND_BIT <= '0';
  --CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
  --CLK0_OUT <= CLKFB_IN;
  CLKDV_BUFG_INST : BUFG
    port map (I => CLKDV_BUF,
              O => CLK_25_0);

  CLKIN_IBUFG_INST : IBUFG
    port map (I => CLKIN_IN,
              O => CLKIN_IBUFG);



  CLK0_BUFG_INST1 : BUFG
    port map (I => CLK0_BUF,
              O => clk_50_0_int);

  DCM_INST : DCM
    generic map(CLK_FEEDBACK           => "1X",
                 CLKDV_DIVIDE          => 2.0,
                 CLKFX_DIVIDE          => 1,
                 CLKFX_MULTIPLY        => 4,
                 CLKIN_DIVIDE_BY_2     => false,
                 CLKIN_PERIOD          => 20.000,
                 CLKOUT_PHASE_SHIFT    => "NONE",
                 DESKEW_ADJUST         => "SYSTEM_SYNCHRONOUS",
                 DFS_FREQUENCY_MODE    => "LOW",
                 DLL_FREQUENCY_MODE    => "LOW",
                 DUTY_CYCLE_CORRECTION => true,
                 FACTORY_JF            => x"8080",
                 PHASE_SHIFT           => 0,
                 STARTUP_WAIT          => false)
    port map (CLKFB    => clk_50_0_int,
              CLKIN    => CLKIN_IBUFG,
              DSSEN    => GND_BIT,
              PSCLK    => GND_BIT,
              PSEN     => GND_BIT,
              PSINCDEC => GND_BIT,
              RST      => RST_IN,
              CLKDV    => CLKDV_BUF,
              CLKFX    => open,
              CLKFX180 => open,
              CLK0     => CLK0_BUF,
              CLK2X    => open,
              CLK2X180 => open,
              CLK90    => open,
              CLK180   => open,
              CLK270   => open,
              LOCKED   => LOCKED_OUT,
              PSDONE   => open,
              STATUS   => open);

end BEHAVIORAL;


